###
# Makefile to build 'app_frontend' application.
#
# Authors:
#   Felipe Girardi 
#   Laura Corssac
#   Marlize Ramos
#   Renan Kummer
###

##
# Constants
##
SRC_DIR = src
OBJ_DIR = out
BIN_DIR = bin
TEST_DIR = tests
HEADERS_DIR = $(SRC_DIR)/headers
COMMON_OBJ_DIR = ../common/$(OBJ_DIR)
INCLUDE_PATH = -I$(HEADERS_DIR) -I../common/include
LIBRARIES = -lpthread
DEBUG_MODE = -g
