
listener:
	g++ -std=c++11 mock_client_listener.c
	g++ -o listener mock_client_listener.o
	./listener localhost


sender:
	g++ -std=c++11 mock_client.c
	g++ -o client mock_client.o
	./client localhost
