sender:
	g++ -std=c++11 -c mock_client_sender.cpp \
    ../common/src/Packet.cpp \
    ../common/src/PacketType.cpp
	g++ -o sender mock_client_sender.o Packet.o PacketType.o
clean:
	rm *.o
	rm listener
	rm sender

Sfelipe:
	make sender
	./sender localhost

Lfelipe:
	make listener
	./listener localhost

build_server:
	g++ -std=c++11 -c mock_client_listener.cpp mock_client_listener.cpp \
	../common/src/Packet.cpp \
	../common/src/PacketType.cpp

listener1:
	make build_server
	g++ -o serverApp mock_client_listener.o Packet.o PacketType.o -lpthread
	./serverApp localhost

